### ISSUE TITLE
Add compatibility with MC 1.21.1

### ISSUE THREAD

**Issue by CptGummiball** [josemmo/yamipa#134] opened 2024-10-04 10:10 UTC
Plugin does not start with Spigot 1.21.1

````
[12:02:57] [Server thread/INFO]: [YamipaPlugin] Enabling YamipaPlugin v1.3.1
[12:02:57] [Server thread/INFO]: [YamipaPlugin] Enabled image animation support
[12:02:57] [Server thread/ERROR]: Error occurred while enabling YamipaPlugin v1.3.1 (Is it up to date?)
java.lang.NoClassDefFoundError: com/comphenix/protocol/injector/player/PlayerInjectionHandler
at io.josemmo.bukkit.plugin.renderer.FakeEntity.(FakeEntity.java:26) ~[?:?]
at io.josemmo.bukkit.plugin.renderer.ImageRenderer.loadConfig(ImageRenderer.java:144) ~[?:?]
at io.josemmo.bukkit.plugin.renderer.ImageRenderer.start(ImageRenderer.java:72) ~[?:?]
at io.josemmo.bukkit.plugin.YamipaPlugin.onEnable(YamipaPlugin.java:116) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:267) ~[spigot-api-1.21.1-R0.1-SNAPSHOT.jar:?]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[spigot-api-1.21.1-R0.1-SNAPSHOT.jar:?]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:492) ~[spigot-api-1.21.1-R0.1-SNAPSHOT.jar:?]
at org.bukkit.craftbukkit.v1_21_R1.CraftServer.enablePlugin(CraftServer.java:575) ~[spigot-1.21.1-R0.1-SNAPSHOT.jar:4290-Spigot-5a6439b-b95736b]
at org.bukkit.craftbukkit.v1_21_R1.CraftServer.enablePlugins(CraftServer.java:489) ~[spigot-1.21.1-R0.1-SNAPSHOT.jar:4290-Spigot-5a6439b-b95736b]
at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:641) ~[spigot-1.21.1-R0.1-SNAPSHOT.jar:4290-Spigot-5a6439b-b95736b]
at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:426) ~[spigot-1.21.1-R0.1-SNAPSHOT.jar:4290-Spigot-5a6439b-b95736b]
at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:269) ~[spigot-1.21.1-R0.1-SNAPSHOT.jar:4290-Spigot-5a6439b-b95736b]
at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1017) ~[spigot-1.21.1-R0.1-SNAPSHOT.jar:4290-Spigot-5a6439b-b95736b]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[spigot-1.21.1-R0.1-SNAPSHOT.jar:4290-Spigot-5a6439b-b95736b]
at java.base/java.lang.Thread.run(Thread.java:1570) [?:?]
Caused by: java.lang.ClassNotFoundException: com.comphenix.protocol.injector.player.PlayerInjectionHandler
at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:160) ~[spigot-api-1.21.1-R0.1-SNAPSHOT.jar:?]
at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:112) ~[spigot-api-1.21.1-R0.1-SNAPSHOT.jar:?]
at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
... 15 more
````

**Comment by wuulfy** [comment] 2024-10-04 15:34
Dupe of #125...

**Closed** 2024-10-05 10:14 UTC
