### ISSUE TITLE
Image doesn't appear/half appears in some cases

### ISSUE THREAD

**Issue by Zoro-6191** [josemmo/yamipa#14] opened 2021-12-08 21:38 UTC
I placed this particular [Image](https://images7.memedroid.com/images/UPLOADED635/5d9775c5d1441.jpeg) in my enderman farm 6x3 dimentions, but some players who were away at the time couldn't render it at all and 1 of my friends could render it only half. He reconnected, spawned on the same chunk and image appeared full. I noticed later on the image appeared half to me as well. 

One of the times, I tried re-placing the image, right clicked kinda fast, and it only said Loading Image or something like that and didnt go away. I thought I didn't place the image as it didnt appear. I reconnected and it was there.

Yamipa 1.2.0
All plugins: [https://paste.md-5.net/uqupixubey](https://paste.md-5.net/uqupixubey)
Paper 1.18 #58

**Comment by josemmo** [comment] 2021-12-12 11:48
Hi, @Zoro-6191!

This might be related to #13.
Does your server have a firewall or some kind of tool for intercepting/blocking network packets?

**Comment by Zoro-6191** [comment] 2021-12-12 11:58
it has protocollib, and no firewalls

**Comment by Zoro-6191** [comment] 2021-12-16 09:18
I use a bare-metal vps and i havent configured any sort of packet filtering yet.

I could try it offline but honestly idk how would i reproduce the bug

One thing i can remember is that my friend wasnt in end dimension when i pasted it, he came there afterwards. Later he reconnected to server while he was in the end and the image rendered perfectly. Different dimensions may be the cause. But idk for sure.

I'm currently travelling so i cant do that debug thing atm, but I'll do it the first chance i get.

**Comment by josemmo** [comment] 2021-12-19 11:37
I still don't know about the image rendered in half (that has to be a network issue), but I've just fixed a [related bug](https://github.com/josemmo/yamipa/commit/bf96e9b44ff127d2367a5843692548656342af23) in [v1.2.1-SNAPSHOT](https://github.com/josemmo/yamipa/releases/tag/v1.2.1-SNAPSHOT), in case you want to try that pre-release.

**Comment by Geoffery10** [comment] 2021-12-21 04:27
I've also had similar issues where images don't load seemingly while switching dimensions (although I haven't seen a half image yet). On my server we have been going in and out of the nether a lot and switching dimensions seems to be the cause.  This can be fixed by logging out and back into the server. 

I'm not exactly sure how you are loading the maps in but is it possible the plugin is losing the player when they switch dimensions or maybe misplacing the image?

**Comment by josemmo** [comment] 2021-12-21 20:48
Hi @Geoffery10,

As in the previous case, have you tried running your Minecraft server locally on your machine or can confirm your hosting provider doesn't have some kind of DDoS packet filtering?

**Comment by Geoffery10** [comment] 2021-12-21 20:53
Hello @josemmo, I should have clarified I locally host my server. I haven't setup any special packet filtering either.

**Comment by josemmo** [comment] 2022-01-07 13:15
Hi everyone,

Unfortunately I haven't been able to reproduce this bug. I'll be closing the issue in a few days.

**Closed** 2022-01-14 18:43 UTC
Labels: status: cannot reproduce
