### ISSUE TITLE
Yamipia causing crashes on latest protocollib

### ISSUE THREAD

**Issue by LuluxClient** [josemmo/yamipa#58] opened 2022-09-16 08:11 UTC
My server crash this morning and after checking the logs it's related to Yamipia and Protocollib: error: https://pastebin.com/E1uhab7H

Crash report: https://pastebin.com/NvMZE2s4

**Comment by josemmo** [comment] 2022-09-16 16:01
Hello @LuluxClient,

Appears to be related to line 67:
https://github.com/josemmo/yamipa/blob/0abaec8db049590e26683211923166bdae0de624/src/main/java/io/josemmo/bukkit/plugin/utils/InteractWithEntityListener.java#L62-L70

Will investigate further. In the meantime, what ProtocolLib version + build number are you using?

**Comment by LuluxClient** [comment] 2022-09-16 16:01
Protocollib 5.0.0 build 600

**Comment by josemmo** [comment] 2022-10-01 10:42
Hello @LuluxClient,

I cannot reproduce this issue on Pufferfish 1.19.2 (build 36). The server you're using (Pufferfish+) requires a license that I don't have, so I cannot test it there.

Why did the crash occur? Did you performed any action in particular?

According to [the documentation](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/entity/LivingEntity.html#getLastTwoTargetBlocks(java.util.Set,int)), `Player#getLastTwoTargetBlocks()` shoudn't throw any exception (which is what's happening). I can surround this call with a try/catch block and call it a day, but I'd like to know if this is a Pufferfish issue or a PaperMC/SpigotMC issue.

**Comment by LuluxClient** [comment] 2022-10-17 15:54
Hey not it happened only once

**Comment by josemmo** [comment] 2022-10-23 10:30
Ok, might have been some weird error from Pufferfish+.

For the moment, I'm closing this issue. If it happens again, feel free to post the new stack trace here (alongside the server version/details) and I'll reopen it.

**Closed by josemmo** 2022-10-23 10:30 UTC
Labels: type: bug, status: cannot reproduce
