### ISSUE TITLE
sometimes image is not shown properly

### ISSUE THREAD

**Issue by aaa8881** [josemmo/yamipa#25] opened 2022-01-18 11:18 UTC
![unknown](https://user-images.githubusercontent.com/8253845/149927472-ef84adf8-7d8f-4693-bf6f-d8458066f586.png)

so some part of image is not properly shown to client. 
This usually gets fixed on relog. 

The server is in 1.17.1 paper , and current screenshot is taken from 1.13.2 client ( as it's written ) , but I experienced few times when while playing in 1.17.1 

protocollib 4.7.0

Yamipa is latest. I'm not very sure what other information I can provide, but if you ask for any other information, I can gladly provide.

**Comment by Dvaelin121** [comment] 2022-01-19 03:23
i've the same problem, and mine not shown after restarting the server. . .

**Comment by aaa8881** [comment] 2022-01-19 14:20
@josemmo regular ping if you've missed it. I sometimes miss checking notification myself when not pinged so.

**Comment by aaa8881** [comment] 2022-01-21 20:00
> Probably the same thing as #24 So try out the pre-release first and see if it's fixed

just updated. will see if issue persists.

**Comment by josemmo** [comment] 2022-01-22 13:48
Possible duplicate of #24.
Closing it for now, will reopen if needed.

**Closed by josemmo** 2022-01-22 13:48 UTC
Labels: type: bug, status: duplicate
