### ISSUE TITLE
Issue with 1.20.6

### ISSUE THREAD

**Issue by Rat3l** [josemmo/yamipa#127] opened 2024-06-09 12:56 UTC
Paper version: paper-1.20.6-137 (10808)
Yamipa Version: YamipaPlugin-1.3.2-SNAPSHOT-b2

Console Error:
[12:50:06] [Server thread/INFO]: [YamipaPlugin] Enabling YamipaPlugin v1.3.2-SNAPSHOT-b2
[12:50:06] [Server thread/ERROR]: Error occurred while enabling YamipaPlugin v1.3.2-SNAPSHOT-b2 (Is it up to date?)
java.lang.ExceptionInInitializerError: null
	at YamipaPlugin-1.3.2-SNAPSHOT-b2.jar/io.josemmo.bukkit.plugin.commands.ImageCommandBridge.register(ImageCommandBridge.java:29) ~[YamipaPlugin-1.3.2-SNAPSHOT-b2.jar:?]
	at YamipaPlugin-1.3.2-SNAPSHOT-b2.jar/io.josemmo.bukkit.plugin.YamipaPlugin.onEnable(YamipaPlugin.java:90) ~[YamipaPlugin-1.3.2-SNAPSHOT-b2.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:519) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:604) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:553) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:675) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:437) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:323) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1136) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.RuntimeException: Failed to get internal classes due to incompatible Minecraft server
	at YamipaPlugin-1.3.2-SNAPSHOT-b2.jar/io.josemmo.bukkit.plugin.utils.Internals.<clinit>(Internals.java:52) ~[YamipaPlugin-1.3.2-SNAPSHOT-b2.jar:?]
	... 14 more
Caused by: java.lang.NoSuchFieldException: vanillaCommandDispatcher
	at java.base/java.lang.Class.getDeclaredField(Class.java:2782) ~[?:?]
	at io.papermc.reflectionrewriter.runtime.AbstractDefaultRulesReflectionProxy.getDeclaredField(AbstractDefaultRulesReflectionProxy.java:90) ~[reflection-rewriter-runtime-0.0.1.jar:?]
	at io.papermc.paper.pluginremap.reflect.PaperReflectionHolder.getDeclaredField(Unknown Source) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
	at YamipaPlugin-1.3.2-SNAPSHOT-b2.jar/io.josemmo.bukkit.plugin.utils.Internals.<clinit>(Internals.java:34) ~[YamipaPlugin-1.3.2-SNAPSHOT-b2.jar:?]
	... 14 more
[12:50:06] [Server thread/INFO]: [YamipaPlugin] Disabling YamipaPlugin v1.3.2-SNAPSHOT-b2

**Comment by josemmo** [comment] 2024-06-09 15:09
Duplicate of #125.

**Closed by josemmo** 2024-06-09 15:09 UTC
