### ISSUE TITLE
Infinite Loading Image on 1.18.1

### ISSUE THREAD

**Issue by Miner28** [josemmo/yamipa#32] opened 2022-02-21 19:15 UTC
Yamipa v1.2.2
Paper- Purpur
![image](https://user-images.githubusercontent.com/1560327/155014440-c2ecc060-13dd-4430-8c22-fd401a93444b.png)
Protocol lib 4.80
![image](https://user-images.githubusercontent.com/1560327/155014715-bcc722be-25a8-49c2-aa98-45d60bc40a31.png)
When trying to place any image .png / .gif or anything else it just goes into infinite loading image and no image appears.

**Comment by josemmo** [comment] 2022-02-22 20:27
Hi, @Miner28!

I cannot reproduce the issue on a new server with:
- Purpur 1.18.1 (rev 1562)
- ProtocolLib v4.8.0-SNAPSHOT-b540
- Yamipa v1.2.2

Could you [enable verbose mode](https://github.com/josemmo/yamipa#configuration) and post here the server logs when placing an image?

**Comment by Miner28** [comment] 2022-02-22 22:44
![image](https://user-images.githubusercontent.com/1560327/155231902-41435211-9922-449c-b650-a497e1c8ee79.png)
Hey did so this is logs when placing the image. Do you want the .log file 
![image](https://user-images.githubusercontent.com/1560327/155232025-2899844f-818c-44a4-9314-ae60095d987c.png)

**Comment by josemmo** [comment] 2022-02-23 07:09
Please paste the relevant logs as text instead of upload images, seems some log entries are missing the timestamp because the screenshot is cropped.

**Comment by Miner28** [comment] 2022-02-23 12:47
Update: Downloaded the plugin from GitHub releases and everything suddenly works fine. All images I tried placing before are now in world. Scattered around everywhere, I clicked right click.

**Comment by josemmo** [comment] 2022-02-24 19:00
Grad to hear! I'm closing the issue.

**Closed by josemmo** 2022-02-24 19:00 UTC
Labels: type: bug, status: cannot reproduce
