### ISSUE TITLE
Exception when reading GIFs without End-of-Information code

### ISSUE THREAD

**Issue by Andreassenemyr** [josemmo/yamipa#30] opened 2022-02-06 12:40 UTC
![5de30a61ca52c6010e571b43f9bfcc3e](https://user-images.githubusercontent.com/32545056/152681190-a0fbc0a4-440f-4f53-a5a4-34274e79edec.png)

**Comment by josemmo** [comment] 2022-02-13 13:12
Hi, @Andreassenemyr!

Could you provide the GIF file that's giving you the error?

**Comment by josemmo** [comment] 2022-03-13 13:10
Can reproduce the issue with [the GIF file](https://user-images.githubusercontent.com/40706932/158047144-85186baf-1c12-4cef-a2c4-ac1b91bb01c3.gif) provided in #33. Thanks, @godModeD!

Building Yamipa from the develop branch now gives a different exception:
```
javax.imageio.IIOException: I/O error reading image!
        at com.sun.imageio.plugins.gif.GIFImageReader.read(GIFImageReader.java:1046) ~[?:?]
        at javax.imageio.ImageReader.read(ImageReader.java:938) ~[?:?]
        at io.josemmo.bukkit.plugin.storage.ImageFile.renderImages(ImageFile.java:131) ~[YamipaPlugin.jar:?]
        at io.josemmo.bukkit.plugin.storage.ImageFile.getMapsAndSubscribe(ImageFile.java:263) ~[YamipaPlugin.jar:?]
        at io.josemmo.bukkit.plugin.storage.ImageFile.getMapsAndSubscribe(ImageFile.java:213) ~[YamipaPlugin.jar:?]
        at io.josemmo.bukkit.plugin.renderer.FakeImage.load(FakeImage.java:342) ~[YamipaPlugin.jar:?]
        at io.josemmo.bukkit.plugin.renderer.FakeImage.lambda$spawn$12(FakeImage.java:378) ~[YamipaPlugin.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: javax.imageio.IIOException: Code buffer limit reached, no End of Image tag present, possibly data is corrupted.
        at com.sun.imageio.plugins.gif.GIFImageReader.read(GIFImageReader.java:1011) ~[?:?]
        ... 12 more
```

**Comment by josemmo** [comment] 2022-03-20 11:31
I've more info on this!

Turns out it's not Yamipa's fault but a an issue with the [GIFImageReader](https://github.com/openjdk/jdk/blob/4df67426ed02f18af0757897acb28b636a317a91/src/java.desktop/share/classes/com/sun/imageio/plugins/gif/GIFImageReader.java#L1010-L1013) class that comes with Java, which expects every frame in a GIF file to end with a "End of Information code" as the [GIF89a spec](https://www.w3.org/Graphics/GIF/spec-gif89a.txt) says. Some ultra-compressed GIF files ignore the spec and skip these codes, so most image decoders/readers are a bit lax and keep rendering the file even without the EOF codes. Unfortunately, that's not the case with JDK.

The three main solutions we have are:

- Implement an alternative GIF decoder from scratch (no way I'm doing that, rather watch paint dry)
- Use another existing GIF decoder (like Apache Commons Imaging) and bundle it Yamipa
- Provide Yamipa with GIF files compliant with the spec

I'm also not a fan of adding more code to Yamipa and making the library more complicated and larger in size, so the second option is discarded. I think the best option is the last one, **just use an online tool like [ezgif.com](https://ezgif.com/repair) to re-encode GIF files and feed that to Yamipa**.

I'm closing this for now, if somebody knows of a quick fix let me know! :)

**Closed by josemmo** 2022-03-20 11:31 UTC
Labels: type: bug, status: confirmed
