### ISSUE TITLE
Error while loading gif

### ISSUE THREAD

**Issue by godModeD** [josemmo/yamipa#33] opened 2022-03-13 06:00 UTC
```
[05:58:34 ERROR]: [YamipaPlugin] Failed to render image(s) from file "/home/minecraft/server/plugins/YamipaPlugin/images/rickroll.gif"
java.lang.ArrayIndexOutOfBoundsException: Index 4096 out of bounds for length 4096
	at com.sun.imageio.plugins.gif.GIFImageReader.read(GIFImageReader.java:1013) ~[?:?]
	at javax.imageio.ImageReader.read(ImageReader.java:938) ~[?:?]
	at io.josemmo.bukkit.plugin.storage.ImageFile.renderImages(ImageFile.java:130) ~[YamipaPlugin-1.2.2.jar:?]
	at io.josemmo.bukkit.plugin.storage.ImageFile.getMapsAndSubscribe(ImageFile.java:257) ~[YamipaPlugin-1.2.2.jar:?]
	at io.josemmo.bukkit.plugin.storage.ImageFile.getMapsAndSubscribe(ImageFile.java:207) ~[YamipaPlugin-1.2.2.jar:?]
	at io.josemmo.bukkit.plugin.renderer.FakeImage.load(FakeImage.java:342) ~[YamipaPlugin-1.2.2.jar:?]
	at io.josemmo.bukkit.plugin.renderer.FakeImage.lambda$spawn$12(FakeImage.java:378) ~[YamipaPlugin-1.2.2.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```
![rickroll](https://user-images.githubusercontent.com/40706932/158047144-85186baf-1c12-4cef-a2c4-ac1b91bb01c3.gif)

**Comment by josemmo** [comment] 2022-03-13 13:03
Duplicate of #30, moving conversation there.

**Closed by josemmo** 2022-03-13 13:03 UTC
Labels: status: duplicate
