### ISSUE TITLE
Server freezes when tapping an item frame

### ISSUE THREAD

**Issue by nakanotti** [josemmo/yamipa#52] opened 2022-08-16 00:18 UTC
PaperMC 1.19.2 (#130)
ProtocolLib 5.0.0  (SNAPSHOT-b597)
Yamipa 1.2.4

Server freezes when tapping an item frame on chest.

**Comment by josemmo** [comment] 2022-08-16 09:46
Duplicate of #51.

**Closed by josemmo** 2022-08-16 09:46 UTC
Labels: status: duplicate
