### ISSUE TITLE
cant place images

### ISSUE THREAD

**Issue by Interesting-exe** [josemmo/yamipa#101] opened 2023-07-09 21:03 UTC
images are loading infinitely when placed. I'm using the latest yamipa build, protcollib v5.10 and paper-550 1.19.4
![2023-07-09_23 58 33](https://github.com/josemmo/yamipa/assets/52731127/1d30bcad-07ad-4442-8458-4c975d6432f5)

**Comment by Interesting-exe** [comment] 2023-07-09 21:44
[latest.log](https://github.com/josemmo/yamipa/files/11996129/latest.log)

**Comment by josemmo** [comment] 2023-07-15 08:39
Hello @Interesting-exe,

Invalidation of cached items is something Yamipa does frequently and is expected, so unfortunately that doesn't seem like the root cause.

- What ProtocolLib version are you using? v5.10 does not exist
- On what version of Yamipa does this bug occur? Please give a concrete version like v1.2.11
- What steps need to be followed to reproduce the bug?
- Do you have other plugins that also depend on ProtocolLib on might interfere with Yamipa?

**Comment by Interesting-exe** [comment] 2023-07-15 12:29
v5.10 is a dev build. the issue also happend on v5.0.0. i use yamipa v1.2.11 but the issue also happend on earlier versions when i tried downgrading. the bug happens whenever someone tries placing an image. it doesn't matter what image, it just wont place it.

**Comment by Interesting-exe** [comment] 2023-07-20 20:11
yeah no other plugin using ProtocolLib

**Comment by josemmo** [comment] 2023-07-22 10:46
Hello @Interesting-exe,

Based on the logs you uploaded, your server does in fact have plugins that depend on ProtocolLib.

I've created a test server with the followings specs to match your setup:
- [paper-1.19.4-550](https://api.papermc.io/v2/projects/paper/versions/1.19.4/builds/550/downloads/paper-1.19.4-550.jar)
- [LuckPerms-Bukkit v5.4.89](https://ci.lucko.me/job/LuckPerms/1503/artifact/bukkit/loader/build/libs/LuckPerms-Bukkit-5.4.89.jar)
- [Vault v1.7.3](https://github.com/MilkBowl/Vault/releases/download/1.7.3/Vault.jar)
- [worldedit-bukkit v2.7.15](https://dev.bukkit.org/projects/worldedit/files/4586220)
- [ProtocoLib v5.1.0-SNAPSHOT-660](https://ci.dmulloy2.net/job/ProtocolLib/660/artifact/build/libs/ProtocolLib.jar)
- [WorldGuard v7.0.8](https://dev.bukkit.org/projects/worldguard/files/4554903/download)
- [EssentialsX v2.20.0](https://github.com/EssentialsX/Essentials/releases/download/2.20.0/EssentialsX-2.20.0.jar)
- [AsceciaCurrencies v1.3](https://github.com/RGG200/Ascecia-Currencies/releases/download/v1.3/AsceciaCurrencies-1.3-Release.jar)
- [GSit v1.4.7](https://github.com/Gecolay/GSit/releases/download/1.4.7/GSit-1.4.7.jar)
- [orebfuscator v5.4.0](https://github.com/Imprex-Development/orebfuscator/releases/download/5.4.0/orebfuscator-plugin-5.4.0.jar)
- [YamipaPlugin v1.2.11](https://github.com/josemmo/yamipa/releases/download/v1.2.11/YamipaPlugin-1.2.11.jar)
- [GrimAC v2.3.43](https://www.spigotmc.org/resources/grim-anticheat.99923/download?version=500985)
- [MarriageMaster v2.7.0.2](https://www.spigotmc.org/resources/marriage-master-mc-1-7-1-20.19273/download?version=501242)
- [Medieval Factions v5.2.0](https://www.spigotmc.org/resources/medieval-factions.79941/download?version=504067)
- [SilkSpawners v7.5.0](https://dev.bukkit.org/projects/silkspawners/files/4612590/download)

I cannot reproduce the bug, images place just fine. The only minor issue is the "Medieval Factions" plugin, that constantly shows an action bars that reads "Wilderness" and might conflict with Yamipa's "Right click a block to continue" message.

If no additional progress is made, I'll need to close the issue.

**Comment by skrrtn** [comment] 2023-10-10 19:15
Having same issue. Here's a little bit of information: 

Server: Paper on 1.20.1-R0.1-SNAPSHOT
Plugins: (yes, its alot)
```
1. ActivityRewarder v2.0.5
2. AdvancedSetSpawn v2.5
3. AureliumSkills
4. Bank v4.6.4-RELEASE
5. BlueMap v3.17
6. Chunky v1.3.92
7. Citizens v2.0.32-SNAPSHOT
8. Coins v1.13.1
9. CommandPanels v3.19.1.4
10. Core v0.6.0
11. CrazyEnchantments v2.1.1
12. DamageIndicator v1.3.7
13. DeathChest v2.0.3
14. DiscordSRV v1.26.2
15. EconomyShopGUI v6.0.9
16. Essentials v2.20.1
17. FancyHolograms v2.0.1
18. FishRewards v1.2.3
19. GriefPrevention v16.18.1
20. HarvestEXP
21. Invsort v2.0.1
22. LagFixer v1.1.5
23. LevelledMobs v3.12.1
24. LibsDisguises v10.0.38
25. lootboxes v1.19.4
26. LuckPerms v5.4.102
27. MiniMOTD v2.0.14
28. MobStatues v1.20.1
29. MobsToEggs v1.7.7
30. Multiverse-Core v4.3.12
31. MyDog v0.2.2
32. Parties v3.2.12
33. PlaceholderAPI v2.11.4
34. Plan v5.5
35. ProtocolLib v5.1.1-SNAPSHOT-669
36. RankSystem v1.3
37. SilkSpawners v7.5.0
38. StoreXP v1.1
39. TabTPS v1.3.21
40. TeleportBow
41. UltraCosmetics v3.3
42. Vault v1.7.3-b131
43. ViaVersion v4.8.1
44. voicechat v2.4.25
45. Waypoints v4.1.0
46. WorldEdit v7.2.15+6463-5ca4dff
47. WorldEditSUI v1.7.2
48. WorldGuard v7.0.9+5934e49
49. YamipaPlugin v1.2.11
```

**Closed** 2023-10-28 18:09 UTC
Labels: type: bug, status: cannot reproduce
